/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sd_205_mongodb;

import com.mongodb.MongoClient;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoDatabase;
import java.awt.Frame;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.bson.Document;

/**
 *
 * @author User
 */
public class MarriageCertificate extends javax.swing.JFrame {

    /**
     * Creates new form MarriageCertificate
     */
    public MarriageCertificate() {
        initComponents();
    }
    
    public void MongoConnect() {

        MongoClient mongo = new MongoClient("localhost", 27017);
        MongoDatabase marriageCollection = mongo.getDatabase("CCE_Pass");
        marriageCollection.createCollection("marriage"); //to create the collection from db
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        homeBtn = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        mLname = new javax.swing.JTextField();
        birthdateField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        mPBcity = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        mPBcountry = new javax.swing.JTextField();
        mPBprov = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        sexCombo = new javax.swing.JComboBox<>();
        mMname = new javax.swing.JTextField();
        mFname = new javax.swing.JTextField();
        issuedidCombo = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        purposeCombo = new javax.swing.JComboBox<>();
        lateRegCombo = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        phoneField = new javax.swing.JTextField();
        jSeparator25 = new javax.swing.JSeparator();
        jLabel30 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        mSFname = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        mSMname = new javax.swing.JTextField();
        jSeparator17 = new javax.swing.JSeparator();
        jSeparator23 = new javax.swing.JSeparator();
        mSLname = new javax.swing.JTextField();
        jSeparator24 = new javax.swing.JSeparator();
        jLabel31 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        dateofmarriageField = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JSeparator();
        placeofmarriageField = new javax.swing.JTextField();
        backBtn = new javax.swing.JButton();
        submitBtn = new javax.swing.JButton();
        minimizebtn = new javax.swing.JLabel();
        closebtn = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator13 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logo.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 90));

        jComboBox1.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Services", "Birth Certificate", "Marriage Certificate", "CENOMAR", "Death Certificate", "Business Permit", "Scholarship", "Voters Certificate", "Appointment", "Suggestions" }));
        jComboBox1.setBorder(null);
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, 120, 30));

        homeBtn.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        homeBtn.setText("Home");
        homeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeBtnMouseClicked(evt);
            }
        });
        jPanel1.add(homeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 60, 30));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 20, 10, 40));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 1130, 10));

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel9.setText("Marriage Certificate");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 10, 230, 60));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel1.setText("Your Information");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel3.setText("Place of Birth (City/Municipality)");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 150, 210, 20));

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel4.setText("Last Name");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 50, 130, -1));

        mLname.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        mLname.setBorder(null);
        jPanel2.add(mLname, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 80, 250, 30));

        birthdateField.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        birthdateField.setText("dd/mm/yy");
        birthdateField.setBorder(null);
        jPanel2.add(birthdateField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 250, 30));

        jLabel11.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel11.setText("First Name");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, 130, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel12.setText("Middle Name");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 50, 130, -1));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 210, 250, 10));

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, 250, 10));

        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 110, 250, 10));

        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 110, 250, 10));

        jLabel10.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel10.setText("Sex");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 40, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel13.setText("Government Issued ID");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 160, 20));

        jLabel14.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel14.setText("Place of Birth (Country)");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 160, 20));

        jLabel15.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel15.setText("Place of Birth (Province)");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 150, 170, 20));

        mPBcity.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        mPBcity.setBorder(null);
        jPanel2.add(mPBcity, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 180, 250, 30));

        jSeparator8.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 250, 10));

        jSeparator9.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 250, 10));

        mPBcountry.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        mPBcountry.setBorder(null);
        jPanel2.add(mPBcountry, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, 250, 30));

        mPBprov.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        mPBprov.setBorder(null);
        jPanel2.add(mPBprov, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 180, 250, 30));

        jSeparator10.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 210, 250, 10));

        jLabel16.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel16.setText("Date of Birth");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 100, 20));

        sexCombo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        sexCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-sex-", "Male", "Female" }));
        sexCombo.setBorder(null);
        jPanel2.add(sexCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 220, 30));

        mMname.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        mMname.setBorder(null);
        jPanel2.add(mMname, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 80, 250, 30));

        mFname.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        mFname.setBorder(null);
        jPanel2.add(mFname, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, 250, 30));

        issuedidCombo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        issuedidCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Choose ID-", "Philippine Identification Card", "Driver’s License Issued by the Land Transportation Office (LTO)", "Philippines National Police (PNP) ID/Police Clearance", "Department of Social Welfare and Development (DSWD) Certification/4Ps ID", "Barangay ID/Certification with picture and signature", "Person with Disability (PWD) ID issued by the National Council on Disability Affairs (NCDA) OR it’s regional counterpart, Office of the Mayor, Office of the Barangay Captain, DSWD Office", "IDs issued by National Government Offices (e,g,.AFP,DAR,DENR,DOH,DOJ) including Government Owned and Controlled Operations", "IDs issued by the Offices of the Local Chief Executives ( Governor, Vice Governor, Mayor, Vice Mayor", "Tax Identification Card (TIN) with a picture and signature issued by the Bureau of International Revenue", "School/ Student ID for currently - enrolled students, 18 years old and above , issued by reputable schools/ college/ universities recognized by the Department of Education", "Barangay ID/ Certification with picture and signature", "Company IDs issued by private entities or institutions registered with, supervised or regulated by Bangkong Sentral ng Pilipinas (BSP), Security Exchange and Commission (SEC)", "Social Security System (SSS) Unified Multi-Purpose ID" }));
        issuedidCombo.setBorder(null);
        jPanel2.add(issuedidCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 890, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 1340, 310));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel2.setText("Additional Information");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 20, 190, -1));

        jLabel25.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel25.setText("Late Registration");
        jPanel3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        purposeCombo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        purposeCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Purpose-", "Passport / Travel", "School Requirement", "Local Employment", "Foreign Employment", "Marriage", "Claims / Benefits / Loans", "Late Registration" }));
        purposeCombo.setBorder(null);
        jPanel3.add(purposeCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 80, 260, 30));

        lateRegCombo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lateRegCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Was the certificate registered late?-", "YES", "NO" }));
        lateRegCombo.setBorder(null);
        jPanel3.add(lateRegCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 270, 30));

        jLabel18.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel18.setText("Purpose of Request");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, 190, -1));

        phoneField.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        phoneField.setBorder(null);
        jPanel3.add(phoneField, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 90, 230, 30));

        jSeparator25.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator25, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 120, 230, 10));

        jLabel30.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel30.setText("Tel/Phone Number");
        jPanel3.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 60, 130, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 600, 1340, 150));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel17.setText("Marriage Place");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 20, -1, -1));

        jLabel26.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel26.setText("First Name");
        jPanel4.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 130, -1));

        mSFname.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        mSFname.setBorder(null);
        jPanel4.add(mSFname, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 170, 30));

        jLabel28.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel28.setText("Middle Name");
        jPanel4.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 130, -1));

        jLabel29.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel29.setText("Place of Marriage");
        jPanel4.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 60, 130, -1));

        mSMname.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        mSMname.setBorder(null);
        jPanel4.add(mSMname, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 170, 30));

        jSeparator17.setForeground(new java.awt.Color(0, 0, 0));
        jPanel4.add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 170, 10));

        jSeparator23.setForeground(new java.awt.Color(0, 0, 0));
        jPanel4.add(jSeparator23, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 170, 10));

        mSLname.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        mSLname.setBorder(null);
        jPanel4.add(mSLname, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, 170, 30));

        jSeparator24.setForeground(new java.awt.Color(0, 0, 0));
        jPanel4.add(jSeparator24, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, 170, 10));

        jLabel31.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel31.setText("Your Spouse's Name ");
        jPanel4.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel20.setText("Marriage Date");
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 20, -1, -1));

        jSeparator11.setForeground(new java.awt.Color(0, 0, 0));
        jPanel4.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 120, 250, 10));

        dateofmarriageField.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        dateofmarriageField.setText("dd/mm/yy");
        dateofmarriageField.setBorder(null);
        jPanel4.add(dateofmarriageField, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 90, 250, 30));

        jLabel32.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel32.setText("Last Name");
        jPanel4.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, 130, -1));

        jLabel33.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel33.setText("Date of Marriage");
        jPanel4.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 60, 130, -1));

        jSeparator12.setForeground(new java.awt.Color(0, 0, 0));
        jPanel4.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 120, 250, 10));

        placeofmarriageField.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        placeofmarriageField.setBorder(null);
        jPanel4.add(placeofmarriageField, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 90, 250, 30));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, 1340, 150));

        backBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        backBtn.setText("Back");
        backBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 3));
        backBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backBtnMouseClicked(evt);
            }
        });
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        jPanel1.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 760, 90, 30));

        submitBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        submitBtn.setText("Submit Request");
        submitBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 51), 3));
        submitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitBtnMouseClicked(evt);
            }
        });
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });
        jPanel1.add(submitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 760, 130, 30));

        minimizebtn.setFont(new java.awt.Font("SansSerif", 0, 36)); // NOI18N
        minimizebtn.setForeground(new java.awt.Color(102, 102, 102));
        minimizebtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minimizebtn.setText("-");
        minimizebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizebtnMouseClicked(evt);
            }
        });
        jPanel1.add(minimizebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1480, 0, 30, 30));

        closebtn.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        closebtn.setForeground(new java.awt.Color(102, 102, 102));
        closebtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        closebtn.setText("x");
        closebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closebtnMouseClicked(evt);
            }
        });
        jPanel1.add(closebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1500, 0, 30, 30));

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel8.setText("Sign-in");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 20, 60, 30));

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel6.setText("Sign-up");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1360, 20, 80, 30));

        jSeparator13.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator13.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator13.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 20, 20, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1530, 850));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeBtnMouseClicked
        Home home = new Home();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homeBtnMouseClicked

    private void backBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseClicked
        Home home = new Home();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBtnMouseClicked

    private void submitBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitBtnMouseClicked
        if (this.mFname.getText().isEmpty() || this.mMname.getText().isEmpty() || this.mLname.getText().isEmpty() || this.birthdateField.getText().isEmpty() || this.mPBcountry.getText().isEmpty() || this.mPBcity.getText().isEmpty() || this.mPBprov.getText().isEmpty() || this.mSFname.getText().isEmpty() || this.mSMname.getText().isEmpty() || this.mSLname.getText().isEmpty() || this.dateofmarriageField.getText().isEmpty() || this.placeofmarriageField.getText().isEmpty() || this.phoneField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Fill out all required fields!", "Alert", JOptionPane.ERROR_MESSAGE);

        } else {
            MongoClient mongo = new MongoClient("localhost", 27017);
            MongoDatabase marriageCollection = mongo.getDatabase("CCE_Pass");
            marriageCollection.getCollection("marriage"); //to get the collection from db
            
            Document d = new Document("sex", this.sexCombo.getSelectedItem());
            d.append("fname", this.mFname.getText());
            d.append("mname", this.mMname.getText());
            d.append("lname", this.mLname.getText());
            d.append("birthdate", this.birthdateField.getText());
            d.append("birthplace(country)", this.mPBcountry.getText());
            d.append("birthplace(province)", this.mPBprov.getText());
            d.append("birthplace(city)", this.mPBcity.getText());
            d.append("gov'tId", this.issuedidCombo.getSelectedItem());
            d.append("sfname", this.mSFname.getText());
            d.append("smname", this.mSMname.getText());
            d.append("slname", this.mSLname.getText());
            d.append("marriage_date", this.dateofmarriageField.getText());
            d.append("marriageplace", this.placeofmarriageField.getText());
            d.append("lateRegField", this.lateRegCombo.getSelectedItem());
            d.append("purpose", this.purposeCombo.getSelectedItem());
            d.append("phone", this.phoneField.getText());
            d.append("status", "Pending");

            marriageCollection.getCollection("marriage").insertOne(d);
            JOptionPane.showMessageDialog(this, "Request Sent Successfully");
        }

        this.sexCombo.setSelectedIndex(0);
        this.mFname.setText("");
        this.mMname.setText("");
        this.mLname.setText("");
        this.birthdateField.setText("");
        this.mPBcountry.setText("");
        this.mPBprov.setText("");
        this.mPBcity.setText("");
        this.issuedidCombo.setSelectedIndex(0);
        this.mSFname.setText("");
        this.mSMname.setText("");
        this.mSLname.setText("");
        this.dateofmarriageField.setText("");
        this.placeofmarriageField.setText("");
        this.lateRegCombo.setSelectedIndex(0);
        this.purposeCombo.setSelectedIndex(0);
        this.phoneField.setText("");
    }//GEN-LAST:event_submitBtnMouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        CCE_Login a = new CCE_Login();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        CCE_Registration a = new CCE_Registration();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void minimizebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizebtnMouseClicked
        this.setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimizebtnMouseClicked

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backBtnActionPerformed

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_submitBtnActionPerformed

    private void closebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closebtnMouseClicked
        this.dispose();
    }//GEN-LAST:event_closebtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MarriageCertificate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MarriageCertificate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MarriageCertificate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MarriageCertificate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MarriageCertificate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField birthdateField;
    private javax.swing.JLabel closebtn;
    private javax.swing.JTextField dateofmarriageField;
    private javax.swing.JLabel homeBtn;
    private javax.swing.JComboBox<String> issuedidCombo;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator23;
    private javax.swing.JSeparator jSeparator24;
    private javax.swing.JSeparator jSeparator25;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JComboBox<String> lateRegCombo;
    private javax.swing.JTextField mFname;
    private javax.swing.JTextField mLname;
    private javax.swing.JTextField mMname;
    private javax.swing.JTextField mPBcity;
    private javax.swing.JTextField mPBcountry;
    private javax.swing.JTextField mPBprov;
    private javax.swing.JTextField mSFname;
    private javax.swing.JTextField mSLname;
    private javax.swing.JTextField mSMname;
    private javax.swing.JLabel minimizebtn;
    private javax.swing.JTextField phoneField;
    private javax.swing.JTextField placeofmarriageField;
    private javax.swing.JComboBox<String> purposeCombo;
    private javax.swing.JComboBox<String> sexCombo;
    private javax.swing.JButton submitBtn;
    // End of variables declaration//GEN-END:variables
}
