/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sd_205_mongodb;

import com.mongodb.MongoClient;
import com.mongodb.client.MongoDatabase;
import javax.swing.JOptionPane;
import org.bson.Document;

/**
 *
 * @author User
 */
public class Scholarship extends javax.swing.JFrame {

    /**
     * Creates new form Scholarship
     */
    public Scholarship() {
        initComponents();
    }

    public void MongoConnect() {
        MongoClient mongo = new MongoClient("localhost", 27017);
        MongoDatabase scholarshipCollection = mongo.getDatabase("CCE_Pass");
        scholarshipCollection.createCollection("scholarship");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        homeBtn = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        sLname = new javax.swing.JTextField();
        birthdateField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        zipcodeField = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        sPlaceofBirth = new javax.swing.JTextField();
        presentaddField = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        sexCombo = new javax.swing.JComboBox<>();
        sMname = new javax.swing.JTextField();
        sFname = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        civilstatusField = new javax.swing.JTextField();
        jSeparator12 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();
        citizenshipField = new javax.swing.JTextField();
        jSeparator13 = new javax.swing.JSeparator();
        phoneField = new javax.swing.JTextField();
        jSeparator25 = new javax.swing.JSeparator();
        jLabel30 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jSeparator29 = new javax.swing.JSeparator();
        jSeparator28 = new javax.swing.JSeparator();
        jLabel35 = new javax.swing.JLabel();
        pastschoolField = new javax.swing.JTextField();
        schooladdField = new javax.swing.JTextField();
        jSeparator18 = new javax.swing.JSeparator();
        schoolsectorField = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        fathersField = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        fatheraddField = new javax.swing.JTextField();
        jSeparator17 = new javax.swing.JSeparator();
        jSeparator23 = new javax.swing.JSeparator();
        fatherphoneField = new javax.swing.JTextField();
        jSeparator19 = new javax.swing.JSeparator();
        jSeparator24 = new javax.swing.JSeparator();
        motheraddField = new javax.swing.JTextField();
        motherphoneField = new javax.swing.JTextField();
        jSeparator26 = new javax.swing.JSeparator();
        jLabel31 = new javax.swing.JLabel();
        mothersField = new javax.swing.JTextField();
        jSeparator27 = new javax.swing.JSeparator();
        jLabel32 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        fathersoccField = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        fatheremployerField = new javax.swing.JTextField();
        jSeparator20 = new javax.swing.JSeparator();
        jSeparator30 = new javax.swing.JSeparator();
        fathereduField = new javax.swing.JTextField();
        jSeparator31 = new javax.swing.JSeparator();
        jLabel39 = new javax.swing.JLabel();
        mothersoccField = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        mothersemployerField = new javax.swing.JTextField();
        jSeparator21 = new javax.swing.JSeparator();
        jSeparator32 = new javax.swing.JSeparator();
        motherseduField = new javax.swing.JTextField();
        jSeparator33 = new javax.swing.JSeparator();
        jSeparator34 = new javax.swing.JSeparator();
        siblingField = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        jSeparator35 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        signup = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        pantawidCombo = new javax.swing.JComboBox<>();
        backBtn = new javax.swing.JButton();
        submitBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logo.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 90));

        jComboBox1.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Services", "Birth Certificate", "Marriage Certificate", "CENOMAR", "Death Certificate", "Business Permit", "Scholarship", "Voters Certificate", "Appointment", "Suggestions" }));
        jComboBox1.setBorder(null);
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, 120, 30));

        homeBtn.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        homeBtn.setText("Home");
        homeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeBtnMouseClicked(evt);
            }
        });
        jPanel1.add(homeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 60, 30));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 20, 10, 40));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 1130, 10));

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel9.setText("Certificate Of Live Birth");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 10, 230, 60));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel1.setText("Personal Information");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel3.setText("Zip Code");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 110, 90, 20));

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel4.setText("Date of Birth (mm/dd/yy)");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 40, 180, -1));

        sLname.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        sLname.setBorder(null);
        jPanel2.add(sLname, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 60, 150, 30));

        birthdateField.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        birthdateField.setBorder(null);
        jPanel2.add(birthdateField, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 60, 150, 30));

        jLabel11.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel11.setText("First Name");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 120, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel12.setText("Middle Name");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, 100, -1));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 160, 150, 10));

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 150, 10));

        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 150, 10));

        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 90, 150, 10));

        jLabel10.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel10.setText("Sex");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel14.setText("Place of Birth ");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 40, 160, 20));

        jLabel15.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel15.setText("Present Address");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 110, 190, 20));

        zipcodeField.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        zipcodeField.setBorder(null);
        jPanel2.add(zipcodeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 130, 150, 30));

        jSeparator8.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 90, 150, 10));

        jSeparator9.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 90, 230, 10));

        sPlaceofBirth.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        sPlaceofBirth.setBorder(null);
        jPanel2.add(sPlaceofBirth, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 60, 230, 30));

        presentaddField.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        presentaddField.setBorder(null);
        jPanel2.add(presentaddField, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 130, 270, 30));

        jSeparator10.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 160, 270, 10));

        jLabel16.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel16.setText("Date of Birth");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 0, 20));

        sexCombo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        sexCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-sex-", "Male", "Female" }));
        sexCombo.setBorder(null);
        jPanel2.add(sexCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 120, 30));

        sMname.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        sMname.setBorder(null);
        jPanel2.add(sMname, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, 150, 30));

        sFname.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        sFname.setBorder(null);
        jPanel2.add(sFname, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 150, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel7.setText("Last Name");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 40, 90, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel18.setText("Civil Status");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 120, -1));

        civilstatusField.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        civilstatusField.setBorder(null);
        jPanel2.add(civilstatusField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 150, 30));

        jSeparator12.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 150, 10));

        jLabel19.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel19.setText("Citizenship");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 120, -1));

        citizenshipField.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        citizenshipField.setBorder(null);
        jPanel2.add(citizenshipField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 150, 30));

        jSeparator13.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 150, 10));

        phoneField.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        phoneField.setBorder(null);
        jPanel2.add(phoneField, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, 230, 30));

        jSeparator25.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator25, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, 230, 10));

        jLabel30.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel30.setText("Tel/Phone Number");
        jPanel2.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, 130, -1));

        jLabel34.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel34.setText("School Last Attended");
        jPanel2.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 180, 180, -1));

        jSeparator29.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator29, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 230, 290, 10));

        jSeparator28.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator28, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 290, 10));

        jLabel35.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel35.setText("School Address");
        jPanel2.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 180, 170, -1));

        pastschoolField.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        pastschoolField.setBorder(null);
        jPanel2.add(pastschoolField, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 200, 290, 30));

        schooladdField.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        schooladdField.setBorder(null);
        jPanel2.add(schooladdField, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 200, 290, 30));

        jSeparator18.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator18, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 230, 290, 10));

        schoolsectorField.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        schoolsectorField.setBorder(null);
        jPanel2.add(schoolsectorField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 290, 30));

        jLabel33.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel33.setText("School Sector");
        jPanel2.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 200, 20));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 1340, 250));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel24.setText("Tel/Phone Number");
        jPanel4.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, 130, -1));

        jLabel26.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel26.setText("Father's Full Name");
        jPanel4.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 130, -1));

        jLabel27.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel27.setText("Mother's Full Name");
        jPanel4.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 130, -1));

        fathersField.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        fathersField.setBorder(null);
        jPanel4.add(fathersField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 170, 30));

        jLabel28.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel28.setText("Address");
        jPanel4.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 130, -1));

        jLabel29.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel29.setText("Tel/Phone Number");
        jPanel4.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, 130, -1));

        fatheraddField.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        fatheraddField.setBorder(null);
        jPanel4.add(fatheraddField, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 170, 30));

        jSeparator17.setForeground(new java.awt.Color(0, 0, 0));
        jPanel4.add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 170, 10));

        jSeparator23.setForeground(new java.awt.Color(0, 0, 0));
        jPanel4.add(jSeparator23, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 170, 10));

        fatherphoneField.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        fatherphoneField.setBorder(null);
        jPanel4.add(fatherphoneField, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, 170, 30));

        jSeparator19.setForeground(new java.awt.Color(0, 0, 0));
        jPanel4.add(jSeparator19, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 170, 10));

        jSeparator24.setForeground(new java.awt.Color(0, 0, 0));
        jPanel4.add(jSeparator24, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, 170, 10));

        motheraddField.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        motheraddField.setBorder(null);
        jPanel4.add(motheraddField, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 170, 30));

        motherphoneField.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        motherphoneField.setBorder(null);
        jPanel4.add(motherphoneField, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, 170, 30));

        jSeparator26.setForeground(new java.awt.Color(0, 0, 0));
        jPanel4.add(jSeparator26, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 170, 10));

        jLabel31.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel31.setText("Family Background");
        jPanel4.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, -1));

        mothersField.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        mothersField.setBorder(null);
        jPanel4.add(mothersField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 170, 30));

        jSeparator27.setForeground(new java.awt.Color(0, 0, 0));
        jPanel4.add(jSeparator27, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, 170, 10));

        jLabel32.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel32.setText("Address");
        jPanel4.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 130, -1));

        jLabel36.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel36.setText("Occupation");
        jPanel4.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 30, 130, -1));

        fathersoccField.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        fathersoccField.setBorder(null);
        jPanel4.add(fathersoccField, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 60, 170, 30));

        jLabel37.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel37.setText("Name of Employer");
        jPanel4.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 30, 130, -1));

        jLabel38.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel38.setText("Highest Educational Attainment");
        jPanel4.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 30, 230, -1));

        fatheremployerField.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        fatheremployerField.setBorder(null);
        jPanel4.add(fatheremployerField, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 60, 170, 30));

        jSeparator20.setForeground(new java.awt.Color(0, 0, 0));
        jPanel4.add(jSeparator20, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 90, 170, 10));

        jSeparator30.setForeground(new java.awt.Color(0, 0, 0));
        jPanel4.add(jSeparator30, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 90, 170, 10));

        fathereduField.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        fathereduField.setBorder(null);
        jPanel4.add(fathereduField, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 60, 230, 30));

        jSeparator31.setForeground(new java.awt.Color(0, 0, 0));
        jPanel4.add(jSeparator31, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 90, 230, 10));

        jLabel39.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel39.setText("Occupation");
        jPanel4.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 100, 130, -1));

        mothersoccField.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        mothersoccField.setBorder(null);
        jPanel4.add(mothersoccField, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 130, 170, 30));

        jLabel40.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel40.setText("Name of Employer");
        jPanel4.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 100, 130, -1));

        jLabel41.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel41.setText("Highest Educational Attainment");
        jPanel4.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 100, 230, -1));

        mothersemployerField.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        mothersemployerField.setBorder(null);
        jPanel4.add(mothersemployerField, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 130, 170, 30));

        jSeparator21.setForeground(new java.awt.Color(0, 0, 0));
        jPanel4.add(jSeparator21, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 160, 170, 10));

        jSeparator32.setForeground(new java.awt.Color(0, 0, 0));
        jPanel4.add(jSeparator32, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 160, 170, 10));

        motherseduField.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        motherseduField.setBorder(null);
        jPanel4.add(motherseduField, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 130, 230, 30));

        jSeparator33.setForeground(new java.awt.Color(0, 0, 0));
        jPanel4.add(jSeparator33, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 160, 230, 10));

        jSeparator34.setForeground(new java.awt.Color(0, 0, 0));
        jPanel4.add(jSeparator34, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 160, 170, 10));

        siblingField.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        siblingField.setBorder(null);
        jPanel4.add(siblingField, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, 340, 30));

        jLabel42.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel42.setText("No. of Siblings in the family, 18 years old and below");
        jPanel4.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, 370, -1));

        jSeparator35.setForeground(new java.awt.Color(0, 0, 0));
        jPanel4.add(jSeparator35, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, 340, 10));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 1340, 250));

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel8.setText("Sign-in");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 20, 60, 30));

        signup.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        signup.setText("Sign-up");
        signup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signupMouseClicked(evt);
            }
        });
        jPanel1.add(signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(1360, 20, 80, 30));

        jSeparator11.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator11.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator11.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 20, 20, 30));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel17.setText("Is your family a beneficiary of the DSWD Pantawid Pamilyang Pilipino Program (4P’s)?");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 650, -1));

        pantawidCombo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pantawidCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Choose-", "YES ", "NO" }));
        pantawidCombo.setBorder(null);
        jPanel3.add(pantawidCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 890, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 620, 1340, 100));

        backBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        backBtn.setText("Back");
        backBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 3));
        backBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backBtnMouseClicked(evt);
            }
        });
        jPanel1.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 740, 90, 30));

        submitBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        submitBtn.setText("Submit Request");
        submitBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 51), 3));
        submitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitBtnMouseClicked(evt);
            }
        });
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });
        jPanel1.add(submitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 730, 130, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1540, 850));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeBtnMouseClicked
        Home home = new Home();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homeBtnMouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        CCE_Login a = new CCE_Login();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void signupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signupMouseClicked
        CCE_Registration a = new CCE_Registration();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_signupMouseClicked

    private void backBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseClicked
        Home home = new Home();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBtnMouseClicked

    private void submitBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitBtnMouseClicked
        if (this.sFname.getText().isEmpty() || this.sLname.getText().isEmpty() || this.birthdateField.getText().isEmpty() || this.sPlaceofBirth.getText().isEmpty() || this.civilstatusField.getText().isEmpty()
                || this.citizenshipField.getText().isEmpty() || this.phoneField.getText().isEmpty() || this.presentaddField.getText().isEmpty() || this.zipcodeField.getText().isEmpty() || this.schoolsectorField.getText().isEmpty() || this.pastschoolField.getText().isEmpty()
                || this.schooladdField.getText().isEmpty() || this.fathersField.getText().isEmpty() || this.phoneField.getText().isEmpty() || this.fathersoccField.getText().isEmpty() || this.fatheremployerField.getText().isEmpty() || this.fathereduField.getText().isEmpty()
                || this.mothersField.getText().isEmpty() || this.motheraddField.getText().isEmpty() || this.motherphoneField.getText().isEmpty() || this.mothersoccField.getText().isEmpty() || this.mothersemployerField.getText().isEmpty() || this.motherseduField.getText().isEmpty() || this.siblingField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Fill out all the fields!", "Alert", JOptionPane.ERROR_MESSAGE);

        } else {
            MongoClient mongo = new MongoClient("localhost", 27017);
            MongoDatabase scholarshipCollection = mongo.getDatabase("CCE_Pass");
            scholarshipCollection.getCollection("scholaship"); //to get the collection from db

            Document d = new Document("sex", this.sexCombo.getSelectedItem());
            d.append("fname", this.sFname.getText());
            d.append("mname", this.sMname.getText());
            d.append("lname", this.sLname.getText());
            d.append("birthdate", this.birthdateField.getText());
            d.append("birthplace", this.sPlaceofBirth.getText());
            d.append("civilStatus", this.civilstatusField.getText());
            d.append("citizenship", this.citizenshipField.getText());
            d.append("phoneField", this.phoneField.getText());
            d.append("presentAdd", this.presentaddField.getText());
            d.append("zipCode", this.zipcodeField.getText());
            d.append("schoolSector", this.schoolsectorField.getText());
            d.append("previousSchool", this.pastschoolField.getText());
            d.append("schoolAdd", this.schooladdField.getText());
            d.append("fathersName", this.fathersField.getText());
            d.append("address", this.fatheraddField.getText());
            d.append("fatherPhone", this.phoneField.getText());
            d.append("occupation", this.fathersoccField.getText());
            d.append("employer", this.fatheremployerField.getText());
            d.append("eduAttainment", this.fathereduField.getText());
            d.append("mothersName", this.mothersField.getText());
            d.append("motherAddress", this.motheraddField.getText());
            d.append("motherPhone", this.motherphoneField.getText());
            d.append("motherOccupation", this.mothersoccField.getText());
            d.append("motherEmployer", this.mothersemployerField.getText());
            d.append("mEduAttainment", this.motherseduField.getText());
            d.append("mEduAttainment", this.siblingField.getText());
            d.append("4P's", this.pantawidCombo.getSelectedItem());
            d.append("status", "Pending");

            scholarshipCollection.getCollection("scholarship").insertOne(d);
            JOptionPane.showMessageDialog(this, "Request Sent Successfully");

        }
        this.sexCombo.setSelectedIndex(0);
        this.sFname.setText("");
        this.sMname.setText("");
        this.sLname.setText("");
        this.birthdateField.setText("");
        this.sPlaceofBirth.setText("");
        this.civilstatusField.setText("");
        this.citizenshipField.setText("");
        this.phoneField.setText("");
        this.presentaddField.setText("");
        this.zipcodeField.setText("");
        this.schoolsectorField.setText("");
        this.pastschoolField.setText("");
        this.schooladdField.setText("");
        this.fathersField.setText("");
        this.fatheraddField.setText("");
        this.phoneField.setText("");
        this.fathersoccField.setText("");
        this.fatheremployerField.setText("");
        this.fathereduField.setText("");
        this.mothersField.setText("");
        this.motheraddField.setText("");
        this.motherphoneField.setText("");
        this.mothersoccField.setText("");
        this.mothersemployerField.setText("");
        this.motherseduField.setText("");
        this.siblingField.setText("");
        this.pantawidCombo.setSelectedIndex(0);

    }//GEN-LAST:event_submitBtnMouseClicked

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_submitBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Scholarship.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Scholarship.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Scholarship.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Scholarship.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Scholarship().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField birthdateField;
    private javax.swing.JTextField citizenshipField;
    private javax.swing.JTextField civilstatusField;
    private javax.swing.JTextField fatheraddField;
    private javax.swing.JTextField fathereduField;
    private javax.swing.JTextField fatheremployerField;
    private javax.swing.JTextField fatherphoneField;
    private javax.swing.JTextField fathersField;
    private javax.swing.JTextField fathersoccField;
    private javax.swing.JLabel homeBtn;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator21;
    private javax.swing.JSeparator jSeparator23;
    private javax.swing.JSeparator jSeparator24;
    private javax.swing.JSeparator jSeparator25;
    private javax.swing.JSeparator jSeparator26;
    private javax.swing.JSeparator jSeparator27;
    private javax.swing.JSeparator jSeparator28;
    private javax.swing.JSeparator jSeparator29;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator30;
    private javax.swing.JSeparator jSeparator31;
    private javax.swing.JSeparator jSeparator32;
    private javax.swing.JSeparator jSeparator33;
    private javax.swing.JSeparator jSeparator34;
    private javax.swing.JSeparator jSeparator35;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField motheraddField;
    private javax.swing.JTextField motherphoneField;
    private javax.swing.JTextField mothersField;
    private javax.swing.JTextField motherseduField;
    private javax.swing.JTextField mothersemployerField;
    private javax.swing.JTextField mothersoccField;
    private javax.swing.JComboBox<String> pantawidCombo;
    private javax.swing.JTextField pastschoolField;
    private javax.swing.JTextField phoneField;
    private javax.swing.JTextField presentaddField;
    private javax.swing.JTextField sFname;
    private javax.swing.JTextField sLname;
    private javax.swing.JTextField sMname;
    private javax.swing.JTextField sPlaceofBirth;
    private javax.swing.JTextField schooladdField;
    private javax.swing.JTextField schoolsectorField;
    private javax.swing.JComboBox<String> sexCombo;
    private javax.swing.JTextField siblingField;
    private javax.swing.JLabel signup;
    private javax.swing.JButton submitBtn;
    private javax.swing.JTextField zipcodeField;
    // End of variables declaration//GEN-END:variables
}
