/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sd_205_mongodb;

import javax.swing.JFrame;

/**
 *
 * @author User
 */
public class StaffHome extends javax.swing.JFrame {

    /**
     * Creates new form StaffHome
     */
    public StaffHome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        votersPane = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        minimizebtn = new javax.swing.JLabel();
        closebtn = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jTextField20 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        jTextField23 = new javax.swing.JTextField();
        jTextField24 = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        jTextField25 = new javax.swing.JTextField();
        jTextField26 = new javax.swing.JTextField();
        jTextField27 = new javax.swing.JTextField();
        jTextField28 = new javax.swing.JTextField();
        jTextField29 = new javax.swing.JTextField();
        jTextField30 = new javax.swing.JTextField();
        jTextField31 = new javax.swing.JTextField();
        jTextField32 = new javax.swing.JTextField();
        jTextField33 = new javax.swing.JTextField();
        jTextField34 = new javax.swing.JTextField();
        jTextField37 = new javax.swing.JTextField();
        jTextField38 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel16 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel40 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jTextField35 = new javax.swing.JTextField();
        jTextField36 = new javax.swing.JTextField();
        jTextField39 = new javax.swing.JTextField();
        jTextField40 = new javax.swing.JTextField();
        jTextField41 = new javax.swing.JTextField();
        jLabel60 = new javax.swing.JLabel();
        jTextField42 = new javax.swing.JTextField();
        jTextField43 = new javax.swing.JTextField();
        jTextField44 = new javax.swing.JTextField();
        jTextField45 = new javax.swing.JTextField();
        jTextField46 = new javax.swing.JTextField();
        jTextField48 = new javax.swing.JTextField();
        jTextField49 = new javax.swing.JTextField();
        jTextField50 = new javax.swing.JTextField();
        jTextField51 = new javax.swing.JTextField();
        jTextField52 = new javax.swing.JTextField();
        jTextField53 = new javax.swing.JTextField();
        jTextField54 = new javax.swing.JTextField();
        jTextField55 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jPanel19 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        jLabel57 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jTextField56 = new javax.swing.JTextField();
        jTextField57 = new javax.swing.JTextField();
        jTextField58 = new javax.swing.JTextField();
        jTextField59 = new javax.swing.JTextField();
        jLabel79 = new javax.swing.JLabel();
        jTextField60 = new javax.swing.JTextField();
        jTextField61 = new javax.swing.JTextField();
        jTextField62 = new javax.swing.JTextField();
        jTextField63 = new javax.swing.JTextField();
        jTextField64 = new javax.swing.JTextField();
        jTextField65 = new javax.swing.JTextField();
        jTextField67 = new javax.swing.JTextField();
        jTextField68 = new javax.swing.JTextField();
        jTextField69 = new javax.swing.JTextField();
        jTextField70 = new javax.swing.JTextField();
        jTextField71 = new javax.swing.JTextField();
        jTextField72 = new javax.swing.JTextField();
        jTextField73 = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jPanel22 = new javax.swing.JPanel();
        jLabel71 = new javax.swing.JLabel();
        jTextField74 = new javax.swing.JTextField();
        jLabel80 = new javax.swing.JLabel();
        jTextField75 = new javax.swing.JTextField();
        voterspanel = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        jPanel24 = new javax.swing.JPanel();
        jLabel72 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jLabel81 = new javax.swing.JLabel();
        jLabel84 = new javax.swing.JLabel();
        jLabel85 = new javax.swing.JLabel();
        jLabel86 = new javax.swing.JLabel();
        jLabel88 = new javax.swing.JLabel();
        jLabel89 = new javax.swing.JLabel();
        jLabel90 = new javax.swing.JLabel();
        jLabel95 = new javax.swing.JLabel();
        jTextField76 = new javax.swing.JTextField();
        jTextField77 = new javax.swing.JTextField();
        jTextField78 = new javax.swing.JTextField();
        jLabel98 = new javax.swing.JLabel();
        jTextField79 = new javax.swing.JTextField();
        jTextField80 = new javax.swing.JTextField();
        jTextField82 = new javax.swing.JTextField();
        jTextField83 = new javax.swing.JTextField();
        jTextField85 = new javax.swing.JTextField();
        jTextField86 = new javax.swing.JTextField();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jPanel25 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel26 = new javax.swing.JPanel();
        jPanel27 = new javax.swing.JPanel();
        jLabel82 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable6 = new javax.swing.JTable();
        jLabel83 = new javax.swing.JLabel();
        jLabel87 = new javax.swing.JLabel();
        jLabel91 = new javax.swing.JLabel();
        jLabel93 = new javax.swing.JLabel();
        jLabel94 = new javax.swing.JLabel();
        jTextField81 = new javax.swing.JTextField();
        jTextField84 = new javax.swing.JTextField();
        jTextField87 = new javax.swing.JTextField();
        jLabel99 = new javax.swing.JLabel();
        jTextField88 = new javax.swing.JTextField();
        jTextField89 = new javax.swing.JTextField();
        jTextField91 = new javax.swing.JTextField();
        jPanel28 = new javax.swing.JPanel();
        jButton18 = new javax.swing.JButton();
        homePane = new javax.swing.JLabel();
        birthPane = new javax.swing.JLabel();
        cenomarPane = new javax.swing.JLabel();
        marriagePane = new javax.swing.JLabel();
        deathPane = new javax.swing.JLabel();
        businessPane = new javax.swing.JLabel();
        scholarshipPane = new javax.swing.JLabel();
        appointmentPane = new javax.swing.JLabel();
        suggestionsPane = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logo.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 90));

        votersPane.setBackground(new java.awt.Color(255, 255, 255));
        votersPane.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        votersPane.setText("Voter's Certificate Request         >");
        votersPane.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 2, true));
        votersPane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        votersPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                votersPaneMouseClicked(evt);
            }
        });
        jPanel1.add(votersPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 240, 40));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 204, 0));
        jSeparator3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 1130, 10));

        minimizebtn.setFont(new java.awt.Font("SansSerif", 0, 36)); // NOI18N
        minimizebtn.setForeground(new java.awt.Color(102, 102, 102));
        minimizebtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minimizebtn.setText("-");
        minimizebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizebtnMouseClicked(evt);
            }
        });
        jPanel1.add(minimizebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1470, 0, 30, 30));

        closebtn.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        closebtn.setForeground(new java.awt.Color(102, 102, 102));
        closebtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        closebtn.setText("x");
        closebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closebtnMouseClicked(evt);
            }
        });
        jPanel1.add(closebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1500, 0, 30, 30));

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 2));
        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane1.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1206, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 645, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Home", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel12.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel1.setText("      Birth Certificate Requests");
        jPanel12.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 200, 30));

        jPanel9.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, 230, 50));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Sex", "First Name", "Middle Name", "Last Name", "Birthdate", "Birthplace(Country)", "Birthplace(Province)", "Birthplace(City)", "Gov't Issued ID", "Father's First Name", "Father's Middle Name", "Father's Last Name", "Mother's First Name", "Mother's Middle Name", "Mother's Last Name", "Late Registration?", "Purpose", "Phone Number", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel9.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 1180, 240));

        jLabel2.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel2.setText("Government Issued ID");
        jPanel9.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 410, 160, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel3.setText("Sex");
        jPanel9.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 40, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel4.setText("Mother's Last Name");
        jPanel9.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 470, 150, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel6.setText("Middle Name");
        jPanel9.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 350, 110, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel7.setText("Last Name");
        jPanel9.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 350, 90, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel10.setText("Birthplace(Country)");
        jPanel9.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 350, 140, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel11.setText("Birthplace(Provice)");
        jPanel9.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 350, 130, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel12.setText("Birthplace(City)");
        jPanel9.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 110, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel13.setText("First Name");
        jPanel9.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 90, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel14.setText("STATUS");
        jPanel9.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 530, 70, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel15.setText("Father's Last Name");
        jPanel9.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 410, 140, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel16.setText("Father's Middle Name");
        jPanel9.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 410, 160, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel18.setText("Mother's Middle Name");
        jPanel9.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 470, 170, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel19.setText("Mother's First Name");
        jPanel9.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 150, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel20.setText("Father's First Name");
        jPanel9.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 410, 140, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel21.setText("Late Registration?");
        jPanel9.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 470, 130, -1));

        jLabel22.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel22.setText("Purpose");
        jPanel9.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 470, 70, -1));

        jLabel23.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel23.setText("Phone Number");
        jPanel9.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 530, 120, -1));
        jPanel9.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 430, 180, -1));
        jPanel9.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 130, -1));
        jPanel9.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 130, -1));
        jPanel9.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, 130, -1));
        jPanel9.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 370, 130, -1));

        jLabel24.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel24.setText("Birthdate");
        jPanel9.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 350, 80, -1));
        jPanel9.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 370, 130, -1));
        jPanel9.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 430, 270, -1));
        jPanel9.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 370, 170, -1));
        jPanel9.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 370, 190, -1));
        jPanel9.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 190, -1));
        jPanel9.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 490, 180, -1));
        jPanel9.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 430, 180, -1));
        jPanel9.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 430, 180, -1));
        jPanel9.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 550, 180, -1));
        jPanel9.add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 490, 180, -1));
        jPanel9.add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 490, 180, -1));
        jPanel9.add(jTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 490, 180, -1));
        jPanel9.add(jTextField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 180, -1));
        jPanel9.add(jTextField19, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 550, 180, -1));

        jButton1.setText("Cancel");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 102), 3, true));
        jPanel9.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 580, 110, 30));

        jButton2.setText("UPDATE");
        jButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 102), 3, true));
        jPanel9.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 580, 110, 30));

        jButton3.setText("Delete");
        jButton3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 102), 3, true));
        jPanel9.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 580, 110, 30));

        jPanel13.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 102), 2, true));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 376, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 66, Short.MAX_VALUE)
        );

        jPanel9.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 560, 380, 70));

        jPanel3.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1210, 650));

        jTabbedPane1.addTab("Birth Certificate Request ", jPanel3);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel15.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel8.setText("      Marriage Certificate Requests");
        jPanel15.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 220, 30));

        jPanel14.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, 250, 50));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Sex", "First Name", "Middle Name", "Last Name", "Birthdate", "Birthplace(Country)", "Birthplace(Province)", "Birthplace(City)", "Gov't Issued ID", "Spouse's First Name", "Spouse's Middle Name", "Spouse's Last Name", "Late Registration?", "Purpose", "Phone Number", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jPanel14.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 1180, 240));

        jLabel17.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel17.setText("Government Issued ID");
        jPanel14.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 410, 160, -1));

        jLabel25.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel25.setText("Sex");
        jPanel14.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 40, -1));

        jLabel27.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel27.setText("Middle Name");
        jPanel14.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 350, 110, -1));

        jLabel28.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel28.setText("Last Name");
        jPanel14.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 350, 90, -1));

        jLabel29.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel29.setText("Birthplace(Country)");
        jPanel14.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 350, 140, -1));

        jLabel30.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel30.setText("Birthplace(Provice)");
        jPanel14.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 350, 130, -1));

        jLabel31.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel31.setText("Birthplace(City)");
        jPanel14.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 110, -1));

        jLabel32.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel32.setText("First Name");
        jPanel14.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 90, -1));

        jLabel33.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel33.setText("STATUS");
        jPanel14.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 530, 70, -1));

        jLabel34.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel34.setText("Spouse's  Last Name");
        jPanel14.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 410, 140, -1));

        jLabel35.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel35.setText("Spouse's  Middle Name");
        jPanel14.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 410, 160, -1));

        jLabel36.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel36.setText("Marriage Place");
        jPanel14.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 470, 170, -1));

        jLabel37.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel37.setText("Marriage Date");
        jPanel14.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 150, -1));

        jLabel38.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel38.setText("Spouse's First Name");
        jPanel14.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 410, 140, -1));

        jLabel39.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel39.setText("Late Registration?");
        jPanel14.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 470, 130, -1));

        jLabel41.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel41.setText("Phone Number");
        jPanel14.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 470, 120, -1));
        jPanel14.add(jTextField20, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 430, 180, -1));
        jPanel14.add(jTextField21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 130, -1));
        jPanel14.add(jTextField22, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 130, -1));
        jPanel14.add(jTextField23, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, 130, -1));
        jPanel14.add(jTextField24, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 370, 130, -1));

        jLabel42.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel42.setText("Birthdate");
        jPanel14.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 350, 80, -1));
        jPanel14.add(jTextField25, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 370, 130, -1));
        jPanel14.add(jTextField26, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 430, 270, -1));
        jPanel14.add(jTextField27, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 370, 170, -1));
        jPanel14.add(jTextField28, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 370, 190, -1));
        jPanel14.add(jTextField29, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 190, -1));
        jPanel14.add(jTextField30, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 490, 180, -1));
        jPanel14.add(jTextField31, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 430, 180, -1));
        jPanel14.add(jTextField32, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 430, 180, -1));
        jPanel14.add(jTextField33, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 550, 180, -1));
        jPanel14.add(jTextField34, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 490, 180, -1));
        jPanel14.add(jTextField37, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 180, -1));
        jPanel14.add(jTextField38, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 490, 180, -1));

        jButton4.setText("Cancel");
        jButton4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 102), 3, true));
        jPanel14.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 580, 110, 30));

        jButton5.setText("UPDATE");
        jButton5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 102), 3, true));
        jPanel14.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 580, 110, 30));

        jButton6.setText("DELETE");
        jButton6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 102), 3, true));
        jPanel14.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 580, 110, 30));

        jPanel16.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 102), 2, true));

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 376, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 66, Short.MAX_VALUE)
        );

        jPanel14.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 560, 380, 70));

        jPanel4.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1210, 650));

        jTabbedPane1.addTab("Marriage Certificate Request", jPanel4);

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel18.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel26.setText("Certificate of No Marriage Requests");
        jPanel18.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 230, 30));

        jPanel17.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, 290, 50));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Sex", "First Name", "Middle Name", "Last Name", "Birthdate", "Birthplace(Country)", "Birthplace(Province)", "Birthplace(City)", "Gov't Issued ID", "Father's First Name", "Father's Middle Name", "Father's Last Name", "Mother's First Name", "Mother's Middle Name", "Mother's Last Name", "Purpose", "Phone Number", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable3);

        jPanel17.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 1180, 240));

        jLabel40.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel40.setText("Government Issued ID");
        jPanel17.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 410, 160, -1));

        jLabel43.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel43.setText("Sex");
        jPanel17.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 40, -1));

        jLabel44.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel44.setText("Mother's Last Name");
        jPanel17.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 470, 150, -1));

        jLabel45.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel45.setText("Middle Name");
        jPanel17.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 350, 110, -1));

        jLabel46.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel46.setText("Last Name");
        jPanel17.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 350, 90, -1));

        jLabel47.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel47.setText("Birthplace(Country)");
        jPanel17.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 350, 140, -1));

        jLabel48.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel48.setText("Birthplace(Provice)");
        jPanel17.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 350, 130, -1));

        jLabel49.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel49.setText("Birthplace(City)");
        jPanel17.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 110, -1));

        jLabel50.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel50.setText("First Name");
        jPanel17.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 90, -1));

        jLabel51.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel51.setText("STATUS");
        jPanel17.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 530, 70, -1));

        jLabel52.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel52.setText("Father's Last Name");
        jPanel17.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 410, 140, -1));

        jLabel53.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel53.setText("Father's Middle Name");
        jPanel17.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 410, 160, -1));

        jLabel54.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel54.setText("Mother's Middle Name");
        jPanel17.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 470, 170, -1));

        jLabel55.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel55.setText("Mother's First Name");
        jPanel17.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 150, -1));

        jLabel56.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel56.setText("Father's First Name");
        jPanel17.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 410, 140, -1));

        jLabel58.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel58.setText("Purpose");
        jPanel17.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 470, 70, -1));

        jLabel59.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel59.setText("Phone Number");
        jPanel17.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 470, 120, -1));
        jPanel17.add(jTextField35, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 430, 180, -1));
        jPanel17.add(jTextField36, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 130, -1));
        jPanel17.add(jTextField39, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 130, -1));
        jPanel17.add(jTextField40, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, 130, -1));
        jPanel17.add(jTextField41, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 370, 130, -1));

        jLabel60.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel60.setText("Birthdate");
        jPanel17.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 350, 80, -1));
        jPanel17.add(jTextField42, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 370, 130, -1));
        jPanel17.add(jTextField43, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 430, 270, -1));
        jPanel17.add(jTextField44, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 370, 170, -1));
        jPanel17.add(jTextField45, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 370, 190, -1));
        jPanel17.add(jTextField46, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 190, -1));
        jPanel17.add(jTextField48, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 430, 180, -1));
        jPanel17.add(jTextField49, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 430, 180, -1));
        jPanel17.add(jTextField50, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 550, 180, -1));
        jPanel17.add(jTextField51, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 490, 180, -1));
        jPanel17.add(jTextField52, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 490, 180, -1));
        jPanel17.add(jTextField53, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 490, 180, -1));
        jPanel17.add(jTextField54, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 180, -1));
        jPanel17.add(jTextField55, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 490, 180, -1));

        jButton7.setText("Cancel");
        jButton7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 102), 3, true));
        jPanel17.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 580, 110, 30));

        jButton8.setText("UPDATE");
        jButton8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 102), 3, true));
        jPanel17.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 580, 110, 30));

        jButton9.setText("Delete");
        jButton9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 102), 3, true));
        jPanel17.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 580, 110, 30));

        jPanel19.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 102), 2, true));

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 376, Short.MAX_VALUE)
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 66, Short.MAX_VALUE)
        );

        jPanel17.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 560, 380, 70));

        jPanel5.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1210, 650));

        jTabbedPane1.addTab("CeNoMar Request", jPanel5);

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel21.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));
        jPanel21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel57.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel57.setText("      Death Certificate Requests");
        jPanel21.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 200, 30));

        jPanel20.add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, 230, 50));

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Sex", "First Name", "Middle Name", "Last Name", "Birthdate", "Birthplace(Country)", "Birthplace(Province)", "Birthplace(City)", "Gov't Issued ID", "Whose Death Certificate?", "First Name", "Middle Name", "Last Name", "Date of Death", "Place of Death", "Late Registration?", "Purpose", "Phone Number", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, true, false, false, false, true, true, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTable4);

        jPanel20.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 1180, 240));

        jLabel61.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel61.setText("Government Issued ID");
        jPanel20.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 410, 160, -1));

        jLabel62.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel62.setText("Sex");
        jPanel20.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 40, -1));

        jLabel63.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel63.setText("Last Name");
        jPanel20.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 470, 150, -1));

        jLabel64.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel64.setText("Middle Name");
        jPanel20.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 350, 110, -1));

        jLabel65.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel65.setText("Last Name");
        jPanel20.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 350, 90, -1));

        jLabel66.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel66.setText("Birthplace(Country)");
        jPanel20.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 350, 140, -1));

        jLabel67.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel67.setText("Birthplace(Provice)");
        jPanel20.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 350, 130, -1));

        jLabel68.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel68.setText("Birthplace(City)");
        jPanel20.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 110, -1));

        jLabel69.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel69.setText("First Name");
        jPanel20.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 90, -1));

        jLabel70.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel70.setText("STATUS");
        jPanel20.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 540, 70, -1));

        jLabel73.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel73.setText("Middle Name");
        jPanel20.add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 470, 170, -1));

        jLabel74.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel74.setText("First Name");
        jPanel20.add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 150, -1));

        jLabel75.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel75.setText("Whose Death Certificate?");
        jPanel20.add(jLabel75, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 410, 190, -1));

        jLabel76.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel76.setText("Late Registration?");
        jPanel20.add(jLabel76, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 540, 130, -1));

        jLabel77.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel77.setText("Purpose");
        jPanel20.add(jLabel77, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 70, -1));

        jLabel78.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel78.setText("Phone Number");
        jPanel20.add(jLabel78, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 540, 120, -1));
        jPanel20.add(jTextField56, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 130, -1));
        jPanel20.add(jTextField57, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 130, -1));
        jPanel20.add(jTextField58, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, 130, -1));
        jPanel20.add(jTextField59, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 370, 130, -1));

        jLabel79.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel79.setText("Birthdate");
        jPanel20.add(jLabel79, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 350, 80, -1));
        jPanel20.add(jTextField60, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 370, 130, -1));
        jPanel20.add(jTextField61, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 430, 270, -1));
        jPanel20.add(jTextField62, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 370, 170, -1));
        jPanel20.add(jTextField63, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 370, 190, -1));
        jPanel20.add(jTextField64, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 190, -1));
        jPanel20.add(jTextField65, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 560, 180, -1));
        jPanel20.add(jTextField67, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 430, 350, -1));
        jPanel20.add(jTextField68, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 560, 180, -1));
        jPanel20.add(jTextField69, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 490, 180, -1));
        jPanel20.add(jTextField70, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 490, 180, -1));
        jPanel20.add(jTextField71, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, 180, -1));
        jPanel20.add(jTextField72, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 180, -1));
        jPanel20.add(jTextField73, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 560, 180, -1));

        jButton10.setText("Cancel");
        jButton10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 102), 3, true));
        jPanel20.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 580, 110, 30));

        jButton11.setText("UPDATE");
        jButton11.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 102), 3, true));
        jPanel20.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 580, 110, 30));

        jButton12.setText("Delete");
        jButton12.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 102), 3, true));
        jPanel20.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 580, 110, 30));

        jPanel22.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 102), 2, true));

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 376, Short.MAX_VALUE)
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 66, Short.MAX_VALUE)
        );

        jPanel20.add(jPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 560, 380, 70));

        jLabel71.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel71.setText("Place of Death");
        jPanel20.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 470, 180, -1));
        jPanel20.add(jTextField74, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 490, 210, -1));

        jLabel80.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel80.setText("Date of Death");
        jPanel20.add(jLabel80, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 470, 210, -1));
        jPanel20.add(jTextField75, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 490, 220, -1));

        jPanel6.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1210, 650));

        jTabbedPane1.addTab("Death Certificate Request", jPanel6);

        javax.swing.GroupLayout voterspanelLayout = new javax.swing.GroupLayout(voterspanel);
        voterspanel.setLayout(voterspanelLayout);
        voterspanelLayout.setHorizontalGroup(
            voterspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1206, Short.MAX_VALUE)
        );
        voterspanelLayout.setVerticalGroup(
            voterspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 645, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Voters Certificate Request", voterspanel);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1206, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 645, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Business Permit Request", jPanel7);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1206, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 645, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Scholarship Application", jPanel8);

        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel23.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel24.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));
        jPanel24.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel72.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel72.setText("Appointment Requests");
        jPanel24.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 150, 30));

        jPanel23.add(jPanel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, 210, 50));

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "First Name", "Middle Name", "Last Name", "Email Address", "Phone Number", "Address", "Appointment Subject", "Appointment Date", "Appointment Time", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(jTable5);

        jPanel23.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 1180, 240));

        jLabel81.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel81.setText("Appointment Date");
        jPanel23.add(jLabel81, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 430, 160, -1));

        jLabel84.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel84.setText("Middle Name");
        jPanel23.add(jLabel84, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, 110, -1));

        jLabel85.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel85.setText("Last Name");
        jPanel23.add(jLabel85, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 350, 90, -1));

        jLabel86.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel86.setText("Phone Number");
        jPanel23.add(jLabel86, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 350, 190, -1));

        jLabel88.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel88.setText("Appoinment Subject");
        jPanel23.add(jLabel88, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 150, -1));

        jLabel89.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel89.setText("First Name");
        jPanel23.add(jLabel89, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 90, -1));

        jLabel90.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel90.setText("STATUS");
        jPanel23.add(jLabel90, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 430, 70, -1));

        jLabel95.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel95.setText("Appoinment Time");
        jPanel23.add(jLabel95, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 430, 140, -1));
        jPanel23.add(jTextField76, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 130, -1));
        jPanel23.add(jTextField77, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, 130, -1));
        jPanel23.add(jTextField78, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 370, 130, -1));

        jLabel98.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel98.setText("Email Address");
        jPanel23.add(jLabel98, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 350, 190, -1));
        jPanel23.add(jTextField79, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 370, 240, -1));
        jPanel23.add(jTextField80, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 450, 180, -1));
        jPanel23.add(jTextField82, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 370, 250, -1));
        jPanel23.add(jTextField83, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 330, -1));
        jPanel23.add(jTextField85, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 450, 180, -1));
        jPanel23.add(jTextField86, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 450, 180, -1));

        jButton13.setText("Cancel");
        jButton13.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 102), 3, true));
        jPanel23.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 580, 110, 30));

        jButton14.setText("UPDATE");
        jButton14.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 102), 3, true));
        jPanel23.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 580, 110, 30));

        jButton15.setText("Delete");
        jButton15.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 102), 3, true));
        jPanel23.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 580, 110, 30));

        jPanel25.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 102), 2, true));

        javax.swing.GroupLayout jPanel25Layout = new javax.swing.GroupLayout(jPanel25);
        jPanel25.setLayout(jPanel25Layout);
        jPanel25Layout.setHorizontalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 376, Short.MAX_VALUE)
        );
        jPanel25Layout.setVerticalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 66, Short.MAX_VALUE)
        );

        jPanel23.add(jPanel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 560, 380, 70));

        jPanel10.add(jPanel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1210, 650));

        jTabbedPane1.addTab("Appointment", jPanel10);

        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel26.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel27.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));
        jPanel27.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel82.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel82.setText("Suggestions/Opinions");
        jPanel27.add(jLabel82, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 150, 30));

        jPanel26.add(jPanel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, 210, 50));

        jTable6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "First Name", "Middle Name", "Last Name", "Email Address", "Subject", "Details"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(jTable6);

        jPanel26.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 1180, 240));

        jLabel83.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel83.setText("Details");
        jPanel26.add(jLabel83, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 450, 160, -1));

        jLabel87.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel87.setText("Middle Name");
        jPanel26.add(jLabel87, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, 110, -1));

        jLabel91.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel91.setText("Last Name");
        jPanel26.add(jLabel91, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 360, 90, -1));

        jLabel93.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel93.setText("Subject");
        jPanel26.add(jLabel93, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 150, -1));

        jLabel94.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel94.setText("First Name");
        jPanel26.add(jLabel94, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 90, -1));
        jPanel26.add(jTextField81, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 220, -1));
        jPanel26.add(jTextField84, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 380, 220, -1));
        jPanel26.add(jTextField87, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 380, 220, -1));

        jLabel99.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel99.setText("Email Address");
        jPanel26.add(jLabel99, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 360, 190, -1));
        jPanel26.add(jTextField88, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 380, 280, -1));
        jPanel26.add(jTextField89, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 470, 760, -1));
        jPanel26.add(jTextField91, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 330, -1));

        jPanel28.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 102), 2, true));

        jButton18.setText("Delete");
        jButton18.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 102), 3, true));

        javax.swing.GroupLayout jPanel28Layout = new javax.swing.GroupLayout(jPanel28);
        jPanel28.setLayout(jPanel28Layout);
        jPanel28Layout.setHorizontalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel28Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        jPanel28Layout.setVerticalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel28Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        jPanel26.add(jPanel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 560, 180, 70));

        jPanel11.add(jPanel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1210, 650));

        jTabbedPane1.addTab("Suggestions", jPanel11);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 1210, 680));

        homePane.setBackground(new java.awt.Color(255, 255, 255));
        homePane.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        homePane.setText("Home                                             >");
        homePane.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 2, true));
        homePane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        homePane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homePaneMouseClicked(evt);
            }
        });
        jPanel1.add(homePane, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 240, 40));

        birthPane.setBackground(new java.awt.Color(255, 255, 255));
        birthPane.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        birthPane.setText("Birth Certificate Request             >");
        birthPane.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 2, true));
        birthPane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        birthPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                birthPaneMouseClicked(evt);
            }
        });
        jPanel1.add(birthPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 240, 40));

        cenomarPane.setBackground(new java.awt.Color(255, 255, 255));
        cenomarPane.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        cenomarPane.setText("CENOMAR Request                     >");
        cenomarPane.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 2, true));
        cenomarPane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cenomarPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cenomarPaneMouseClicked(evt);
            }
        });
        jPanel1.add(cenomarPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 240, 40));

        marriagePane.setBackground(new java.awt.Color(255, 255, 255));
        marriagePane.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        marriagePane.setText("Marriage Certificate Request     >");
        marriagePane.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 2, true));
        marriagePane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        marriagePane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                marriagePaneMouseClicked(evt);
            }
        });
        jPanel1.add(marriagePane, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 240, 40));

        deathPane.setBackground(new java.awt.Color(255, 255, 255));
        deathPane.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        deathPane.setText("Death Certificate Request           >");
        deathPane.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 2, true));
        deathPane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        deathPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deathPaneMouseClicked(evt);
            }
        });
        jPanel1.add(deathPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 240, 40));

        businessPane.setBackground(new java.awt.Color(255, 255, 255));
        businessPane.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        businessPane.setText("Business Permit Request             >");
        businessPane.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 2, true));
        businessPane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        businessPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                businessPaneMouseClicked(evt);
            }
        });
        jPanel1.add(businessPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 240, 40));

        scholarshipPane.setBackground(new java.awt.Color(255, 255, 255));
        scholarshipPane.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        scholarshipPane.setText("Scholarship                                   >");
        scholarshipPane.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 2, true));
        scholarshipPane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        scholarshipPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                scholarshipPaneMouseClicked(evt);
            }
        });
        jPanel1.add(scholarshipPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 610, 240, 40));

        appointmentPane.setBackground(new java.awt.Color(255, 255, 255));
        appointmentPane.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        appointmentPane.setText("Appointment                                 >");
        appointmentPane.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 2, true));
        appointmentPane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        appointmentPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                appointmentPaneMouseClicked(evt);
            }
        });
        jPanel1.add(appointmentPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 680, 240, 40));

        suggestionsPane.setBackground(new java.awt.Color(255, 255, 255));
        suggestionsPane.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        suggestionsPane.setText("Suggestions                                  >");
        suggestionsPane.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 2, true));
        suggestionsPane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        suggestionsPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                suggestionsPaneMouseClicked(evt);
            }
        });
        jPanel1.add(suggestionsPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 750, 240, 40));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 20, 10, 40));

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel9.setText("Manage Requests");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 10, 350, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1540, 860));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void votersPaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_votersPaneMouseClicked
                jTabbedPane1.setSelectedIndex(5);

    }//GEN-LAST:event_votersPaneMouseClicked

    private void minimizebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizebtnMouseClicked
        this.setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimizebtnMouseClicked

    private void closebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closebtnMouseClicked
        this.dispose();
    }//GEN-LAST:event_closebtnMouseClicked

    private void homePaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homePaneMouseClicked
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_homePaneMouseClicked

    private void birthPaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_birthPaneMouseClicked
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_birthPaneMouseClicked

    private void cenomarPaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cenomarPaneMouseClicked
        jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_cenomarPaneMouseClicked

    private void marriagePaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_marriagePaneMouseClicked
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_marriagePaneMouseClicked

    private void deathPaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deathPaneMouseClicked
        jTabbedPane1.setSelectedIndex(4);
    }//GEN-LAST:event_deathPaneMouseClicked

    private void businessPaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_businessPaneMouseClicked
        jTabbedPane1.setSelectedIndex(6);
    }//GEN-LAST:event_businessPaneMouseClicked

    private void scholarshipPaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scholarshipPaneMouseClicked
        jTabbedPane1.setSelectedIndex(7);
    }//GEN-LAST:event_scholarshipPaneMouseClicked

    private void appointmentPaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_appointmentPaneMouseClicked
        jTabbedPane1.setSelectedIndex(8);
    }//GEN-LAST:event_appointmentPaneMouseClicked

    private void suggestionsPaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_suggestionsPaneMouseClicked
        jTabbedPane1.setSelectedIndex(9);
    }//GEN-LAST:event_suggestionsPaneMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StaffHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StaffHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StaffHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StaffHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StaffHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel appointmentPane;
    private javax.swing.JLabel birthPane;
    private javax.swing.JLabel businessPane;
    private javax.swing.JLabel cenomarPane;
    private javax.swing.JLabel closebtn;
    private javax.swing.JLabel deathPane;
    private javax.swing.JLabel homePane;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JLabel jLabel98;
    private javax.swing.JLabel jLabel99;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JTable jTable6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField29;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField30;
    private javax.swing.JTextField jTextField31;
    private javax.swing.JTextField jTextField32;
    private javax.swing.JTextField jTextField33;
    private javax.swing.JTextField jTextField34;
    private javax.swing.JTextField jTextField35;
    private javax.swing.JTextField jTextField36;
    private javax.swing.JTextField jTextField37;
    private javax.swing.JTextField jTextField38;
    private javax.swing.JTextField jTextField39;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField40;
    private javax.swing.JTextField jTextField41;
    private javax.swing.JTextField jTextField42;
    private javax.swing.JTextField jTextField43;
    private javax.swing.JTextField jTextField44;
    private javax.swing.JTextField jTextField45;
    private javax.swing.JTextField jTextField46;
    private javax.swing.JTextField jTextField48;
    private javax.swing.JTextField jTextField49;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField50;
    private javax.swing.JTextField jTextField51;
    private javax.swing.JTextField jTextField52;
    private javax.swing.JTextField jTextField53;
    private javax.swing.JTextField jTextField54;
    private javax.swing.JTextField jTextField55;
    private javax.swing.JTextField jTextField56;
    private javax.swing.JTextField jTextField57;
    private javax.swing.JTextField jTextField58;
    private javax.swing.JTextField jTextField59;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField60;
    private javax.swing.JTextField jTextField61;
    private javax.swing.JTextField jTextField62;
    private javax.swing.JTextField jTextField63;
    private javax.swing.JTextField jTextField64;
    private javax.swing.JTextField jTextField65;
    private javax.swing.JTextField jTextField67;
    private javax.swing.JTextField jTextField68;
    private javax.swing.JTextField jTextField69;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField70;
    private javax.swing.JTextField jTextField71;
    private javax.swing.JTextField jTextField72;
    private javax.swing.JTextField jTextField73;
    private javax.swing.JTextField jTextField74;
    private javax.swing.JTextField jTextField75;
    private javax.swing.JTextField jTextField76;
    private javax.swing.JTextField jTextField77;
    private javax.swing.JTextField jTextField78;
    private javax.swing.JTextField jTextField79;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField80;
    private javax.swing.JTextField jTextField81;
    private javax.swing.JTextField jTextField82;
    private javax.swing.JTextField jTextField83;
    private javax.swing.JTextField jTextField84;
    private javax.swing.JTextField jTextField85;
    private javax.swing.JTextField jTextField86;
    private javax.swing.JTextField jTextField87;
    private javax.swing.JTextField jTextField88;
    private javax.swing.JTextField jTextField89;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField jTextField91;
    private javax.swing.JLabel marriagePane;
    private javax.swing.JLabel minimizebtn;
    private javax.swing.JLabel scholarshipPane;
    private javax.swing.JLabel suggestionsPane;
    private javax.swing.JLabel votersPane;
    private javax.swing.JPanel voterspanel;
    // End of variables declaration//GEN-END:variables
}
